/*******************************************************************************
* File Name: ADC_ACCELEROMETER.h
* Version 1.10
*
* Description:
*  This file contains the function prototypes and constants used in
*  the Sequencing Successive Approximation ADC Component.
*
* Note:
*
********************************************************************************
* Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions,
* disclaimers, and limitations in the end user license agreement accompanying
* the software package with which this file was provided.
*******************************************************************************/

#if !defined(CY_ADC_SAR_SEQ_ADC_ACCELEROMETER_H)
#define CY_ADC_SAR_SEQ_ADC_ACCELEROMETER_H


/***************************************
*      Data Struct Definition
***************************************/

/* Sleep Mode API Support */
typedef struct
{
    uint8 enableState;
} ADC_ACCELEROMETER_BACKUP_STRUCT;


/**************************************
*    Enumerated Types and Parameters
**************************************/

/*  Clock Source setting constants */
#define ADC_ACCELEROMETER__EXTERNAL 0
#define ADC_ACCELEROMETER__INTERNAL 1

/*  Sample Mode setting constants */
#define ADC_ACCELEROMETER__FREERUNNING 0
#define ADC_ACCELEROMETER__HARDWARESOC 1

/*  Reference type setting constants */
#define ADC_ACCELEROMETER__VDDA_2 0
#define ADC_ACCELEROMETER__VDDA 1
#define ADC_ACCELEROMETER__INTERNAL1024 2
#define ADC_ACCELEROMETER__INTERNAL1024BYPASSED 3
#define ADC_ACCELEROMETER__INTERNALVREF 4
#define ADC_ACCELEROMETER__INTERNALVREFBYPASSED 5
#define ADC_ACCELEROMETER__VDDA_2BYPASSED 6
#define ADC_ACCELEROMETER__EXTERNALVREF 7

/* Input buffer gain setting constants */
#define ADC_ACCELEROMETER__DISABLED 0
#define ADC_ACCELEROMETER__ONE 1
#define ADC_ACCELEROMETER__TWO 2
#define ADC_ACCELEROMETER__FOUR 3
#define ADC_ACCELEROMETER__EIGHT 4
#define ADC_ACCELEROMETER__SIXTEEN 5

/* Negative input setting sonstants in single ended mode */
#define ADC_ACCELEROMETER__VSS 0
#define ADC_ACCELEROMETER__VREF 1
#define ADC_ACCELEROMETER__OTHER 2

/* Compare mode setting constants:
*    Mode0 - Disable
*    Mode1 - Result < Low_Limit
*    Mode2 - Low_Limit <= Result < High_Limit
*    Mode3 - High_Limit <= Result
*    Mode4 - (Result < Low_Limit) or (High_Limit <= Result)
*/
#define ADC_ACCELEROMETER__MODE0 0
#define ADC_ACCELEROMETER__MODE1 1
#define ADC_ACCELEROMETER__MODE2 2
#define ADC_ACCELEROMETER__MODE3 3

#define ADC_ACCELEROMETER__RES8 0
#define ADC_ACCELEROMETER__RES10 1

#define ADC_ACCELEROMETER__RIGHT 0
#define ADC_ACCELEROMETER__LEFT 1

#define ADC_ACCELEROMETER__FSIGNED 1
#define ADC_ACCELEROMETER__FUNSIGNED 0

#define ADC_ACCELEROMETER__ACCUMULATE 0
#define ADC_ACCELEROMETER__FIXEDRESOLUTION 1




/***************************************
*    Initial Parameter Constants
***************************************/
#define ADC_ACCELEROMETER_DEFAULT_SAMPLE_MODE_SEL        (0u)
#define ADC_ACCELEROMETER_DEFAULT_VREF_SEL               (1u)
#define ADC_ACCELEROMETER_DEFAULT_NEG_INPUT_SEL          (0u)
#define ADC_ACCELEROMETER_DEFAULT_ALT_RESOLUTION_SEL     (0u)
#define ADC_ACCELEROMETER_DEFAULT_JUSTIFICATION_SEL      (0u)
#define ADC_ACCELEROMETER_DEFAULT_DIFF_RESULT_FORMAT_SEL (1u)
#define ADC_ACCELEROMETER_DEFAULT_SE_RESULT_FORMAT_SEL   (1u)
#define ADC_ACCELEROMETER_DEFAULT_CLOCK_SOURCE           (1u)
#define ADC_ACCELEROMETER_DEFAULT_VREF_MV_VALUE          (3300)
#define ADC_ACCELEROMETER_DEFAULT_BUFFER_GAIN            (0u)
#define ADC_ACCELEROMETER_DEFAULT_AVG_SAMPLES_NUM        (0u)
#define ADC_ACCELEROMETER_DEFAULT_AVG_SAMPLES_DIV        (int16)(0x100u >> (7u - 0u))
#define ADC_ACCELEROMETER_DEFAULT_AVG_MODE               (1u)
#define ADC_ACCELEROMETER_MAX_RESOLUTION                 (12u)
#define ADC_ACCELEROMETER_DEFAULT_LOW_LIMIT              (0u)
#define ADC_ACCELEROMETER_DEFAULT_HIGH_LIMIT             (2047u)
#define ADC_ACCELEROMETER_DEFAULT_COMPARE_MODE           (0u)
#define ADC_ACCELEROMETER_DEFAULT_ACLKS_NUM              (4u)
#define ADC_ACCELEROMETER_DEFAULT_BCLKS_NUM              (4u)
#define ADC_ACCELEROMETER_DEFAULT_CCLKS_NUM              (4u)
#define ADC_ACCELEROMETER_DEFAULT_DCLKS_NUM              (4u)
#define ADC_ACCELEROMETER_TOTAL_CHANNELS_NUM             (3u)
#define ADC_ACCELEROMETER_SEQUENCED_CHANNELS_NUM         (3u)
#define ADC_ACCELEROMETER_DEFAULT_EN_CHANNELS            (7u)
#define ADC_ACCELEROMETER_NOMINAL_CLOCK_FREQ             (2000000)
#define ADC_ACCELEROMETER_INJ_CHANNEL_ENABLED            (0u)
#define ADC_ACCELEROMETER_IRQ_REMOVE                     (0u)
/* Determines whether the configuration contains external negative input. */
#define ADC_ACCELEROMETER_SINGLE_PRESENT                 (0u)
#define ADC_ACCELEROMETER_CHANNELS_MODE                  (0u)
#define ADC_ACCELEROMETER_MAX_CHANNELS_EN_MASK           (0xffffu >> (16u - ADC_ACCELEROMETER_SEQUENCED_CHANNELS_NUM))


/***************************************
*        Function Prototypes
***************************************/

void ADC_ACCELEROMETER_Start(void);
void ADC_ACCELEROMETER_Stop(void);
void ADC_ACCELEROMETER_Init(void);
void ADC_ACCELEROMETER_Enable(void);
void ADC_ACCELEROMETER_StartConvert(void);
void ADC_ACCELEROMETER_StopConvert(void);
uint32 ADC_ACCELEROMETER_IsEndConversion(uint32 retMode);
int16 ADC_ACCELEROMETER_GetResult16(uint32 chan);
void ADC_ACCELEROMETER_SetChanMask(uint32 mask);
void ADC_ACCELEROMETER_SetLowLimit(uint32 lowLimit);
void ADC_ACCELEROMETER_SetHighLimit(uint32 highLimit);
void ADC_ACCELEROMETER_SetLimitMask(uint32 mask);
void ADC_ACCELEROMETER_SetSatMask(uint32 mask);
void ADC_ACCELEROMETER_SetOffset(uint32 chan, int16 offset);
void ADC_ACCELEROMETER_SetGain(uint32 chan, int32 adcGain);
#if(ADC_ACCELEROMETER_INJ_CHANNEL_ENABLED)
    void ADC_ACCELEROMETER_EnableInjection(void);
#endif /* ADC_ACCELEROMETER_INJ_CHANNEL_ENABLED */
#if(ADC_ACCELEROMETER_DEFAULT_JUSTIFICATION_SEL == ADC_ACCELEROMETER__RIGHT)
    int16 ADC_ACCELEROMETER_CountsTo_mVolts(uint32 chan, int16 adcCounts);
    int32 ADC_ACCELEROMETER_CountsTo_uVolts(uint32 chan, int16 adcCounts);
    float32 ADC_ACCELEROMETER_CountsTo_Volts(uint32 chan, int16 adcCounts);
#endif /* End ADC_ACCELEROMETER_DEFAULT_JUSTIFICATION_SEL == ADC_ACCELEROMETER__RIGHT */
void ADC_ACCELEROMETER_Sleep(void);
void ADC_ACCELEROMETER_Wakeup(void);
void ADC_ACCELEROMETER_SaveConfig(void);
void ADC_ACCELEROMETER_RestoreConfig(void);

CY_ISR_PROTO( ADC_ACCELEROMETER_ISR );


/**************************************
*           API Constants
**************************************/
/* Constants for Sleep mode states */
#define ADC_ACCELEROMETER_STARTED                    (0x02u)
#define ADC_ACCELEROMETER_ENABLED                    (0x01u)
#define ADC_ACCELEROMETER_DISABLED                   (0x00u)

/*   Constants for IsEndConversion() "retMode" parameter  */
#define ADC_ACCELEROMETER_RETURN_STATUS              (0x01u)
#define ADC_ACCELEROMETER_WAIT_FOR_RESULT            (0x02u)
#define ADC_ACCELEROMETER_RETURN_STATUS_INJ          (0x04u)
#define ADC_ACCELEROMETER_WAIT_FOR_RESULT_INJ        (0x08u)

#define ADC_ACCELEROMETER_MAX_FREQUENCY              (18000000)       /*18Mhz*/

#define ADC_ACCELEROMETER_RESOLUTION_12              (12u)
#define ADC_ACCELEROMETER_RESOLUTION_10              (10u)
#define ADC_ACCELEROMETER_RESOLUTION_8               (8u)

#define ADC_ACCELEROMETER_10US_DELAY                 (10u)

#define ADC_ACCELEROMETER_10V_COUNTS                 (10.0F)
#define ADC_ACCELEROMETER_10MV_COUNTS                (10000)
#define ADC_ACCELEROMETER_10UV_COUNTS                (10000000L)


/***************************************
* Global variables external identifier
***************************************/

extern uint8 ADC_ACCELEROMETER_initVar;
extern volatile int16 ADC_ACCELEROMETER_offset[ADC_ACCELEROMETER_TOTAL_CHANNELS_NUM];
extern volatile int32 ADC_ACCELEROMETER_countsPer10Volt[ADC_ACCELEROMETER_TOTAL_CHANNELS_NUM];


/***************************************
*              Registers
***************************************/

#define ADC_ACCELEROMETER_SAR_CTRL_REG                (*(reg32 *) ADC_ACCELEROMETER_cy_psoc4_sar__SAR_CTRL )
#define ADC_ACCELEROMETER_SAR_CTRL_PTR                ( (reg32 *) ADC_ACCELEROMETER_cy_psoc4_sar__SAR_CTRL )

#define ADC_ACCELEROMETER_SAR_SAMPLE_CTRL_REG         (*(reg32 *) ADC_ACCELEROMETER_cy_psoc4_sar__SAR_SAMPLE_CTRL )
#define ADC_ACCELEROMETER_SAR_SAMPLE_CTRL_PTR         ( (reg32 *) ADC_ACCELEROMETER_cy_psoc4_sar__SAR_SAMPLE_CTRL )

#define ADC_ACCELEROMETER_SAR_SAMPLE_TIME01_REG       (*(reg32 *) ADC_ACCELEROMETER_cy_psoc4_sar__SAR_SAMPLE_TIME01 )
#define ADC_ACCELEROMETER_SAR_SAMPLE_TIME01_PTR       ( (reg32 *) ADC_ACCELEROMETER_cy_psoc4_sar__SAR_SAMPLE_TIME01 )

#define ADC_ACCELEROMETER_SAR_SAMPLE_TIME23_REG       (*(reg32 *) ADC_ACCELEROMETER_cy_psoc4_sar__SAR_SAMPLE_TIME23 )
#define ADC_ACCELEROMETER_SAR_SAMPLE_TIME23_PTR       ( (reg32 *) ADC_ACCELEROMETER_cy_psoc4_sar__SAR_SAMPLE_TIME23 )

#define ADC_ACCELEROMETER_SAR_RANGE_THRES_REG         (*(reg32 *) ADC_ACCELEROMETER_cy_psoc4_sar__SAR_RANGE_THRES )
#define ADC_ACCELEROMETER_SAR_RANGE_THRES_PTR         ( (reg32 *) ADC_ACCELEROMETER_cy_psoc4_sar__SAR_RANGE_THRES )

#define ADC_ACCELEROMETER_SAR_RANGE_COND_REG          (*(reg32 *) ADC_ACCELEROMETER_cy_psoc4_sar__SAR_RANGE_COND )
#define ADC_ACCELEROMETER_SAR_RANGE_COND_PTR          ( (reg32 *) ADC_ACCELEROMETER_cy_psoc4_sar__SAR_RANGE_COND )

#define ADC_ACCELEROMETER_SAR_CHAN_EN_REG             (*(reg32 *) CYREG_SAR_CHAN_EN )
#define ADC_ACCELEROMETER_SAR_CHAN_EN_PTR             ( (reg32 *) CYREG_SAR_CHAN_EN )

#define ADC_ACCELEROMETER_SAR_START_CTRL_REG          (*(reg32 *) CYREG_SAR_START_CTRL )
#define ADC_ACCELEROMETER_SAR_START_CTRL_PTR          ( (reg32 *) CYREG_SAR_START_CTRL )

#define ADC_ACCELEROMETER_SAR_DFT_CTRL_REG            (*(reg32 *) CYREG_SAR_DFT_CTRL )
#define ADC_ACCELEROMETER_SAR_DFT_CTRL_PTR            ( (reg32 *) CYREG_SAR_DFT_CTRL )

#define ADC_ACCELEROMETER_SAR_CHAN_CONFIG_REG         (*(reg32 *) CYREG_SAR_CHAN_CONFIG00 )
#define ADC_ACCELEROMETER_SAR_CHAN_CONFIG_PTR         ( (reg32 *) CYREG_SAR_CHAN_CONFIG00 )
#define ADC_ACCELEROMETER_SAR_CHAN_CONFIG_IND         CYREG_SAR_CHAN_CONFIG00

#define ADC_ACCELEROMETER_SAR_CHAN_WORK_REG           (*(reg32 *) CYREG_SAR_CHAN_WORK00 )
#define ADC_ACCELEROMETER_SAR_CHAN_WORK_PTR           ( (reg32 *) CYREG_SAR_CHAN_WORK00 )

#define ADC_ACCELEROMETER_SAR_CHAN_RESULT_REG         (*(reg32 *) CYREG_SAR_CHAN_RESULT00 )
#define ADC_ACCELEROMETER_SAR_CHAN_RESULT_PTR         ( (reg32 *) CYREG_SAR_CHAN_RESULT00 )
#define ADC_ACCELEROMETER_SAR_CHAN_RESULT_IND         CYREG_SAR_CHAN_RESULT00

#define ADC_ACCELEROMETER_SAR_CHAN0_RESULT_REG         (*(reg32 *) CYREG_SAR_CHAN_RESULT00 )
#define ADC_ACCELEROMETER_SAR_CHAN0_RESULT_PTR         ( (reg32 *) CYREG_SAR_CHAN_RESULT00 )

#define ADC_ACCELEROMETER_SAR_CHAN1_RESULT_REG         (*(reg32 *) CYREG_SAR_CHAN_RESULT01 )
#define ADC_ACCELEROMETER_SAR_CHAN1_RESULT_PTR         ( (reg32 *) CYREG_SAR_CHAN_RESULT01 )

#define ADC_ACCELEROMETER_SAR_CHAN2_RESULT_REG         (*(reg32 *) CYREG_SAR_CHAN_RESULT02 )
#define ADC_ACCELEROMETER_SAR_CHAN2_RESULT_PTR         ( (reg32 *) CYREG_SAR_CHAN_RESULT02 )

#define ADC_ACCELEROMETER_SAR_CHAN3_RESULT_REG         (*(reg32 *) CYREG_SAR_CHAN_RESULT03 )
#define ADC_ACCELEROMETER_SAR_CHAN3_RESULT_PTR         ( (reg32 *) CYREG_SAR_CHAN_RESULT03 )

#define ADC_ACCELEROMETER_SAR_CHAN4_RESULT_REG         (*(reg32 *) CYREG_SAR_CHAN_RESULT04 )
#define ADC_ACCELEROMETER_SAR_CHAN4_RESULT_PTR         ( (reg32 *) CYREG_SAR_CHAN_RESULT04 )

#define ADC_ACCELEROMETER_SAR_CHAN5_RESULT_REG         (*(reg32 *) CYREG_SAR_CHAN_RESULT05 )
#define ADC_ACCELEROMETER_SAR_CHAN5_RESULT_PTR         ( (reg32 *) CYREG_SAR_CHAN_RESULT05 )

#define ADC_ACCELEROMETER_SAR_CHAN6_RESULT_REG         (*(reg32 *) CYREG_SAR_CHAN_RESULT06 )
#define ADC_ACCELEROMETER_SAR_CHAN6_RESULT_PTR         ( (reg32 *) CYREG_SAR_CHAN_RESULT06 )

#define ADC_ACCELEROMETER_SAR_CHAN7_RESULT_REG         (*(reg32 *) CYREG_SAR_CHAN_RESULT07 )
#define ADC_ACCELEROMETER_SAR_CHAN7_RESULT_PTR         ( (reg32 *) CYREG_SAR_CHAN_RESULT07 )

#define ADC_ACCELEROMETER_SAR_CHAN_WORK_VALID_REG     (*(reg32 *) CYREG_SAR_CHAN_WORK_VALID)
#define ADC_ACCELEROMETER_SAR_CHAN_WORK_VALID_PTR     ( (reg32 *) CYREG_SAR_CHAN_WORK_VALID)

#define ADC_ACCELEROMETER_SAR_CHAN_RESULT_VALID_REG   ( *(reg32 *) CYREG_SAR_CHAN_RESULT_VALID )
#define ADC_ACCELEROMETER_SAR_CHAN_RESULT_VALID_PTR   ( (reg32 *) CYREG_SAR_CHAN_RESULT_VALID )

#define ADC_ACCELEROMETER_SAR_STATUS_REG              (*(reg32 *) ADC_ACCELEROMETER_cy_psoc4_sar__SAR_STATUS )
#define ADC_ACCELEROMETER_SAR_STATUS_PTR              ( (reg32 *) ADC_ACCELEROMETER_cy_psoc4_sar__SAR_STATUS )

#define ADC_ACCELEROMETER_SAR_AVG_START_REG           (*(reg32 *) ADC_ACCELEROMETER_cy_psoc4_sar__SAR_AVG_STAT )
#define ADC_ACCELEROMETER_SAR_AVG_START_PTR           ( (reg32 *) ADC_ACCELEROMETER_cy_psoc4_sar__SAR_AVG_STAT )

#define ADC_ACCELEROMETER_SAR_INTR_REG                (*(reg32 *) ADC_ACCELEROMETER_cy_psoc4_sar__SAR_INTR )
#define ADC_ACCELEROMETER_SAR_INTR_PTR                ( (reg32 *) ADC_ACCELEROMETER_cy_psoc4_sar__SAR_INTR )

#define ADC_ACCELEROMETER_SAR_INTR_SET_REG            (*(reg32 *) ADC_ACCELEROMETER_cy_psoc4_sar__SAR_INTR_SET )
#define ADC_ACCELEROMETER_SAR_INTR_SET_PTR            ( (reg32 *) ADC_ACCELEROMETER_cy_psoc4_sar__SAR_INTR_SET )

#define ADC_ACCELEROMETER_SAR_INTR_MASK_REG           (*(reg32 *) ADC_ACCELEROMETER_cy_psoc4_sar__SAR_INTR_MASK )
#define ADC_ACCELEROMETER_SAR_INTR_MASK_PTR           ( (reg32 *) ADC_ACCELEROMETER_cy_psoc4_sar__SAR_INTR_MASK )

#define ADC_ACCELEROMETER_SAR_INTR_MASKED_REG         (*(reg32 *) ADC_ACCELEROMETER_cy_psoc4_sar__SAR_INTR_MASKED )
#define ADC_ACCELEROMETER_SAR_INTR_MASKED_PTR         ( (reg32 *) ADC_ACCELEROMETER_cy_psoc4_sar__SAR_INTR_MASKED )

#define ADC_ACCELEROMETER_SAR_SATURATE_INTR_REG       (*(reg32 *) CYREG_SAR_SATURATE_INTR )
#define ADC_ACCELEROMETER_SAR_SATURATE_INTR_PTR       ( (reg32 *) CYREG_SAR_SATURATE_INTR )

#define ADC_ACCELEROMETER_SAR_SATURATE_INTR_SET_REG   (*(reg32 *) ADC_ACCELEROMETER_cy_psoc4_sar__SAR_SATURATE_INTR_SET )
#define ADC_ACCELEROMETER_SAR_SATURATE_INTR_SET_PTR   ( (reg32 *) ADC_ACCELEROMETER_cy_psoc4_sar__SAR_SATURATE_INTR_SET )

#define ADC_ACCELEROMETER_SAR_SATURATE_INTR_MASK_REG  (*(reg32 *) ADC_ACCELEROMETER_cy_psoc4_sar__SAR_SATURATE_INTR_MASK )
#define ADC_ACCELEROMETER_SAR_SATURATE_INTR_MASK_PTR  ( (reg32 *) ADC_ACCELEROMETER_cy_psoc4_sar__SAR_SATURATE_INTR_MASK )

#define ADC_ACCELEROMETER_SAR_SATURATE_INTR_MASKED_REG \
                                                 (*(reg32 *) ADC_ACCELEROMETER_cy_psoc4_sar__SAR_SATURATE_INTR_MASKED )
#define ADC_ACCELEROMETER_SAR_SATURATE_INTR_MASKED_PTR \
                                                 ( (reg32 *) ADC_ACCELEROMETER_cy_psoc4_sar__SAR_SATURATE_INTR_MASKED )

#define ADC_ACCELEROMETER_SAR_RANGE_INTR_REG          (*(reg32 *) CYREG_SAR_RANGE_INTR )
#define ADC_ACCELEROMETER_SAR_RANGE_INTR_PTR          ( (reg32 *) CYREG_SAR_RANGE_INTR )

#define ADC_ACCELEROMETER_SAR_RANGE_INTR_SET_REG      (*(reg32 *) ADC_ACCELEROMETER_cy_psoc4_sar__SAR_RANGE_INTR_SET )
#define ADC_ACCELEROMETER_SAR_RANGE_INTR_SET_PTR      ( (reg32 *) ADC_ACCELEROMETER_cy_psoc4_sar__SAR_RANGE_INTR_SET )

#define ADC_ACCELEROMETER_SAR_RANGE_INTR_MASK_REG     (*(reg32 *) ADC_ACCELEROMETER_cy_psoc4_sar__SAR_RANGE_INTR_MASK )
#define ADC_ACCELEROMETER_SAR_RANGE_INTR_MASK_PTR     ( (reg32 *) ADC_ACCELEROMETER_cy_psoc4_sar__SAR_RANGE_INTR_MASK )

#define ADC_ACCELEROMETER_SAR_RANGE_INTR_MASKED_REG   (*(reg32 *) ADC_ACCELEROMETER_cy_psoc4_sar__SAR_RANGE_INTR_MASKED )
#define ADC_ACCELEROMETER_SAR_RANGE_INTR_MASKED_PTR   ( (reg32 *) ADC_ACCELEROMETER_cy_psoc4_sar__SAR_RANGE_INTR_MASKED )

#define ADC_ACCELEROMETER_SAR_INTR_CAUSE_REG          (*(reg32 *) ADC_ACCELEROMETER_cy_psoc4_sar__SAR_INTR_CAUSE )
#define ADC_ACCELEROMETER_SAR_INTR_CAUSE_PTR          ( (reg32 *) ADC_ACCELEROMETER_cy_psoc4_sar__SAR_INTR_CAUSE )

#define ADC_ACCELEROMETER_SAR_INJ_CHAN_CONFIG_REG     (*(reg32 *) CYREG_SAR_INJ_CHAN_CONFIG)
#define ADC_ACCELEROMETER_SAR_INJ_CHAN_CONFIG_PTR     ( (reg32 *) CYREG_SAR_INJ_CHAN_CONFIG)

#define ADC_ACCELEROMETER_SAR_INJ_RESULT_REG          (*(reg32 *) CYREG_SAR_INJ_RESULT )
#define ADC_ACCELEROMETER_SAR_INJ_RESULT_PTR          ( (reg32 *) CYREG_SAR_INJ_RESULT )

#define ADC_ACCELEROMETER_MUX_SWITCH0_REG             (*(reg32 *)  CYREG_SAR_MUX_SWITCH0 )
#define ADC_ACCELEROMETER_MUX_SWITCH0_PTR             ( (reg32 *)  CYREG_SAR_MUX_SWITCH0 )

#define ADC_ACCELEROMETER_MUX_SWITCH_HW_CTRL_REG      (*(reg32 *)  CYREG_SAR_MUX_SWITCH_HW_CTRL )
#define ADC_ACCELEROMETER_MUX_SWITCH_HW_CTRL_PTR      ( (reg32 *)  CYREG_SAR_MUX_SWITCH_HW_CTRL )

#define ADC_ACCELEROMETER_PUMP_CTRL_REG               (*(reg32 *)  CYREG_SAR_PUMP_CTRL )
#define ADC_ACCELEROMETER_PUMP_CTRL_PTR               ( (reg32 *)  CYREG_SAR_PUMP_CTRL )

#define ADC_ACCELEROMETER_ANA_TRIM_REG                (*(reg32 *)  CYREG_SAR_ANA_TRIM )
#define ADC_ACCELEROMETER_ANA_TRIM_PTR                ( (reg32 *)  CYREG_SAR_ANA_TRIM )

#define ADC_ACCELEROMETER_WOUNDING_REG                (*(reg32 *)  CYREG_SAR_WOUNDING )
#define ADC_ACCELEROMETER_WOUNDING_PTR                ( (reg32 *)  CYREG_SAR_WOUNDING )


/**************************************
*       Register Constants
**************************************/
#define ADC_ACCELEROMETER_INTC_NUMBER                (ADC_ACCELEROMETER_IRQ__INTC_NUMBER)
#define ADC_ACCELEROMETER_INTC_PRIOR_NUMBER          (ADC_ACCELEROMETER_IRQ__INTC_PRIOR_NUM)

/* defines for CTRL register */
#define ADC_ACCELEROMETER_VREF_INTERNAL1024          (0x00000040Lu)
#define ADC_ACCELEROMETER_VREF_EXTERNAL              (0x00000050Lu)
#define ADC_ACCELEROMETER_VREF_VDDA_2                (0x00000060Lu)
#define ADC_ACCELEROMETER_VREF_VDDA                  (0x00000070Lu)
#define ADC_ACCELEROMETER_VREF_INTERNAL1024BYPASSED  (0x000000C0Lu)
#define ADC_ACCELEROMETER_VREF_VDDA_2BYPASSED        (0x000000E0Lu)
#define ADC_ACCELEROMETER_VREF_INTERNALVREF          (0x00000000Lu)
#define ADC_ACCELEROMETER_VREF_INTERNALVREFBYPASSED  (0x00000000Lu)

#define ADC_ACCELEROMETER_NEG_VSSA_KELVIN            (0x00000000Lu)
#define ADC_ACCELEROMETER_NEG_VSSA                   (0x00000200Lu)
#define ADC_ACCELEROMETER_NEG_VREF                   (0x00000E00Lu)
#if(ADC_ACCELEROMETER_TOTAL_CHANNELS_NUM > 1u)
    #define ADC_ACCELEROMETER_NEG_OTHER              (uint16)((uint16)ADC_ACCELEROMETER_cy_psoc4_sarmux_8__VNEG << 9u)
#else
    #define ADC_ACCELEROMETER_NEG_OTHER              (0)
#endif /* ADC_ACCELEROMETER_TOTAL_CHANNELS_NUM > 1u */

#define ADC_ACCELEROMETER_SAR_HW_CTRL_NEGVREF        (0x00002000Lu)

#define ADC_ACCELEROMETER_NORMAL_PWR                 (0x00000000Lu)
#define ADC_ACCELEROMETER_HALF_PWR                   (0x01000000Lu)
#define ADC_ACCELEROMETER_MORE_PWR                   (0x02000000Lu)
#define ADC_ACCELEROMETER_QUARTER_PWR                (0x03000000Lu)

#define ADC_ACCELEROMETER_DSI_SYNC_CONFIG            (0x10000000Lu)
#define ADC_ACCELEROMETER_DSI_MODE                   (0x20000000Lu)
#define ADC_ACCELEROMETER_SWITCH_DISABLE             (0x40000000Lu)
#define ADC_ACCELEROMETER_ENABLE                     (0x80000000Lu)

/* defines for SAMPLE_CTRL register */
#define ADC_ACCELEROMETER_ALT_RESOLUTION_10BIT       (0x00000001Lu)
#define ADC_ACCELEROMETER_ALT_RESOLUTION_8BIT        (0x00000000Lu)

#define ADC_ACCELEROMETER_DATA_ALIGN_LEFT            (0x00000002Lu)
#define ADC_ACCELEROMETER_DATA_ALIGN_RIGHT           (0x00000000Lu)

#define ADC_ACCELEROMETER_SE_SIGNED_RESULT           (0x00000004Lu)
#define ADC_ACCELEROMETER_SE_UNSIGNED_RESULT         (0x00000000Lu)

#define ADC_ACCELEROMETER_DIFF_SIGNED_RESULT         (0x00000008Lu)
#define ADC_ACCELEROMETER_DIFF_UNSIGNED_RESULT       (0x00000000Lu)

#define ADC_ACCELEROMETER_AVG_CNT_OFFSET             (4u)
#define ADC_ACCELEROMETER_AVG_CNT_MASK               (0x00000070Lu)
#define ADC_ACCELEROMETER_AVG_SHIFT                  (0x00000080Lu)

#define ADC_ACCELEROMETER_CONTINUOUS_EN              (0x00010000Lu)
#define ADC_ACCELEROMETER_DSI_TRIGGER_EN             (0x00020000Lu)
#define ADC_ACCELEROMETER_DSI_TRIGGER_LEVEL          (0x00040000Lu)
#define ADC_ACCELEROMETER_DSI_SYNC_TRIGGER           (0x00080000Lu)
#define ADC_ACCELEROMETER_EOS_DSI_OUT_EN             (0x80000000Lu)

/* defines for SAMPLE_TIME01 / SAMPLE_TIME23 registers */
#define ADC_ACCELEROMETER_SAMPLE_TIME13_OFFSET       (16u)
#define ADC_ACCELEROMETER_SAMPLE_TIME02_MASK         (0x000003FFLu)
#define ADC_ACCELEROMETER_SAMPLE_TIME13_MASK         (0x03FF0000Lu)

/* defines for RANGE_THRES registers */
#define ADC_ACCELEROMETER_RANGE_HIGH_OFFSET          (16u)
#define ADC_ACCELEROMETER_RANGE_HIGH_MASK            (0xFFFF0000Lu)
#define ADC_ACCELEROMETER_RANGE_LOW_MASK             (0x0000FFFFLu)

/* defines for RANGE_COND register */
/* Compare mode setting constants:
*    BELOW   - Result < Low_Limit
*    INSIDE  - Low_Limit <= Result < High_Limit
*    ABOVE   - High_Limit <= Result
*    OUTSIDE - (Result < Low_Limit) or (High_Limit <= Result)
*/
#define ADC_ACCELEROMETER_CMP_MODE_BELOW             (0x00000000Lu)
#define ADC_ACCELEROMETER_CMP_MODE_INSIDE            (0x40000000Lu)
#define ADC_ACCELEROMETER_CMP_MODE_ABOVE             (0x80000000Lu)
#define ADC_ACCELEROMETER_CMP_MODE_OUTSIDE           (0xC0000000Lu)
#define ADC_ACCELEROMETER_CMP_OFFSET                 (30u)

/* defines for _START_CTRL register */
#define ADC_ACCELEROMETER_FW_TRIGGER                 (0x00000001Lu)

/* defines for DFT_CTRL register */
#define ADC_ACCELEROMETER_DLY_INC                    (0x00000001Lu)
#define ADC_ACCELEROMETER_HIZ                        (0x00000002Lu)
#define ADC_ACCELEROMETER_DFT_INC_MASK               (0x000F0000Lu)
#define ADC_ACCELEROMETER_DFT_OUTC_MASK              (0x00700000Lu)
#define ADC_ACCELEROMETER_SEL_CSEL_DFT_MASK          (0x0F000000Lu)
/* configuration for clock speed > 9 Mhz based on
* characterization results 
*/
#define ADC_ACCELEROMETER_SEL_CSEL_DFT_CHAR          (0x03000000Lu)
#define ADC_ACCELEROMETER_EN_CSEL_DFT                (0x10000000Lu)
#define ADC_ACCELEROMETER_DCEN                       (0x20000000Lu)
#define ADC_ACCELEROMETER_ADFT_OVERRIDE              (0x80000000Lu)

/* defines for CHAN_CONFIG / DIE_CHAN_CONFIG register
*  and channelsConfig parameter 
*/
#define ADC_ACCELEROMETER_SARMUX_VIRT_SELECT         (0x00000070Lu)
#define ADC_ACCELEROMETER_DIFFERENTIAL_EN            (0x00000100Lu)
#define ADC_ACCELEROMETER_ALT_RESOLUTION_ON          (0x00000200Lu)
#define ADC_ACCELEROMETER_AVERAGING_EN               (0x00000400Lu)

#define ADC_ACCELEROMETER_SAMPLE_TIME_SEL_SHIFT      (12u)
#define ADC_ACCELEROMETER_SAMPLE_TIME_SEL_MASK       (0x00003000Lu)

#define ADC_ACCELEROMETER_CHANNEL_CONFIG_MASK        (0x00003700Lu)

/* for CHAN_CONFIG only */
#define ADC_ACCELEROMETER_DSI_OUT_EN                 (0x80000000Lu)

/* for INJ_CHAN_CONFIG only */
#define ADC_ACCELEROMETER_INJ_TAILGATING             (0x40000000Lu)
#define ADC_ACCELEROMETER_INJ_CHAN_EN                (0x80000000Lu)

/* defines for CHAN_WORK register */
#define ADC_ACCELEROMETER_SAR_WRK_MAX_12BIT          (0x00001000Lu)
#define ADC_ACCELEROMETER_SAR_WRK_MAX_10BIT          (0x00000400Lu)
#define ADC_ACCELEROMETER_SAR_WRK_MAX_8BIT           (0x00000100Lu)

/* defines for CHAN_RESULT register */
#define ADC_ACCELEROMETER_RESULT_MASK                (0x0000FFFFLu)
#define ADC_ACCELEROMETER_SATURATE_INTR_MIR          (0x20000000Lu)
#define ADC_ACCELEROMETER_RANGE_INTR_MIR             (0x40000000Lu)
#define ADC_ACCELEROMETER_CHAN_RESULT_VALID_MIR      (0x80000000Lu)

/* defines for INTR_MASK register */
#define ADC_ACCELEROMETER_EOS_MASK                   (0x00000001Lu)
#define ADC_ACCELEROMETER_OVERFLOW_MASK              (0x00000002Lu)
#define ADC_ACCELEROMETER_FW_COLLISION_MASK          (0x00000004Lu)
#define ADC_ACCELEROMETER_DSI_COLLISION_MASK         (0x00000008Lu)
#define ADC_ACCELEROMETER_INJ_EOC_MASK               (0x00000010Lu)
#define ADC_ACCELEROMETER_INJ_SATURATE_MASK          (0x00000020Lu)
#define ADC_ACCELEROMETER_INJ_RANGE_MASK             (0x00000040Lu)
#define ADC_ACCELEROMETER_INJ_COLLISION_MASK         (0x00000080Lu)

/* defines for INJ_RESULT register */
#define ADC_ACCELEROMETER_INJ_COLLISION_INTR_MIR     (0x10000000Lu)
#define ADC_ACCELEROMETER_INJ_SATURATE_INTR_MIR      (0x20000000Lu)
#define ADC_ACCELEROMETER_INJ_RANGE_INTR_MIR         (0x40000000Lu)
#define ADC_ACCELEROMETER_INJ_EOC_INTR_MIR           (0x80000000Lu)

/* defines for MUX_SWITCH0 register */
#define ADC_ACCELEROMETER_MUX_FW_VSSA_VMINUS         (0x00010000Lu)

/* defines for PUMP_CTRL register */
#define ADC_ACCELEROMETER_PUMP_CTRL_ENABLED          (0x80000000Lu)

/* additional defines for channelsConfig parameter */
#define ADC_ACCELEROMETER_IS_SATURATE_EN_MASK        (0x00000001Lu)
#define ADC_ACCELEROMETER_IS_RANGE_CTRL_EN_MASK      (0x00000002Lu)

/* defines for WOUNDING register */
#define ADC_ACCELEROMETER_WOUNDING_12BIT             (0x00000000Lu)
#define ADC_ACCELEROMETER_WOUNDING_10BIT             (0x00000001Lu)
#define ADC_ACCELEROMETER_WOUNDING_8BIT              (0x00000002Lu)

/* Trim value based on characterization */
#define ADC_ACCELEROMETER_TRIM_COEF                  (2u)

#if(ADC_ACCELEROMETER_MAX_RESOLUTION == ADC_ACCELEROMETER_RESOLUTION_10)
    #define ADC_ACCELEROMETER_ALT_WOUNDING           ADC_ACCELEROMETER_WOUNDING_10BIT 
#else
    #define ADC_ACCELEROMETER_ALT_WOUNDING           ADC_ACCELEROMETER_WOUNDING_8BIT 
#endif /* ADC_ACCELEROMETER_MAX_RESOLUTION == ADC_ACCELEROMETER_RESOLUTION_10 */

#if(ADC_ACCELEROMETER_DEFAULT_VREF_SEL == ADC_ACCELEROMETER__VDDA_2)
    #define ADC_ACCELEROMETER_DEFAULT_VREF_SOURCE    ADC_ACCELEROMETER_VREF_VDDA_2
#elif(ADC_ACCELEROMETER_DEFAULT_VREF_SEL == ADC_ACCELEROMETER__VDDA)
    #define ADC_ACCELEROMETER_DEFAULT_VREF_SOURCE    ADC_ACCELEROMETER_VREF_VDDA
#elif(ADC_ACCELEROMETER_DEFAULT_VREF_SEL == ADC_ACCELEROMETER__INTERNAL1024)
    #define ADC_ACCELEROMETER_DEFAULT_VREF_SOURCE    ADC_ACCELEROMETER_VREF_INTERNAL1024
#elif(ADC_ACCELEROMETER_DEFAULT_VREF_SEL == ADC_ACCELEROMETER__INTERNAL1024BYPASSED)
    #define ADC_ACCELEROMETER_DEFAULT_VREF_SOURCE    ADC_ACCELEROMETER_VREF_INTERNAL1024BYPASSED
#elif(ADC_ACCELEROMETER_DEFAULT_VREF_SEL == ADC_ACCELEROMETER__INTERNALVREF)
    #define ADC_ACCELEROMETER_DEFAULT_VREF_SOURCE    ADC_ACCELEROMETER_VREF_INTERNALVREF
#elif(ADC_ACCELEROMETER_DEFAULT_VREF_SEL == ADC_ACCELEROMETER__INTERNALVREFBYPASSED)
    #define ADC_ACCELEROMETER_DEFAULT_VREF_SOURCE    ADC_ACCELEROMETER_VREF_INTERNALVREFBYPASSED
#elif(ADC_ACCELEROMETER_DEFAULT_VREF_SEL == ADC_ACCELEROMETER__VDDA_2BYPASSED)
    #define ADC_ACCELEROMETER_DEFAULT_VREF_SOURCE    ADC_ACCELEROMETER_VREF_VDDA_2BYPASSED
#else
    #define ADC_ACCELEROMETER_DEFAULT_VREF_SOURCE    ADC_ACCELEROMETER_VREF_EXTERNAL
#endif /* ADC_ACCELEROMETER_DEFAULT_VREF_SEL == ADC_ACCELEROMETER__VDDA_2 */

#if(ADC_ACCELEROMETER_DEFAULT_NEG_INPUT_SEL == ADC_ACCELEROMETER__VSS)
    /* Connect NEG input of SARADC to VSSA close to the SARADC for single channel mode */
    #if(ADC_ACCELEROMETER_TOTAL_CHANNELS_NUM == 1u)
        #define ADC_ACCELEROMETER_DEFAULT_SE_NEG_INPUT    ADC_ACCELEROMETER_NEG_VSSA
    #else
        #define ADC_ACCELEROMETER_DEFAULT_SE_NEG_INPUT    ADC_ACCELEROMETER_NEG_VSSA_KELVIN
    #endif /* (ADC_ACCELEROMETER_TOTAL_CHANNELS_NUM == 1u) */    
    /* Do not connect VSSA to VMINUS when one channel in differential mode used */
    #if((ADC_ACCELEROMETER_TOTAL_CHANNELS_NUM == 1u) && (ADC_ACCELEROMETER_CHANNELS_MODE != 0u))
        #define ADC_ACCELEROMETER_DEFAULT_MUX_SWITCH0     0u
    #else    /* miltiple channels or one single channel */
        #define ADC_ACCELEROMETER_DEFAULT_MUX_SWITCH0     ADC_ACCELEROMETER_MUX_FW_VSSA_VMINUS
    #endif /* (ADC_ACCELEROMETER_TOTAL_CHANNELS_NUM == 1u) */
#elif(ADC_ACCELEROMETER_DEFAULT_NEG_INPUT_SEL == ADC_ACCELEROMETER__VREF)
    /* Do not connect VNEG to VREF when one channel in differential mode used */
    #if((ADC_ACCELEROMETER_TOTAL_CHANNELS_NUM == 1u) && (ADC_ACCELEROMETER_CHANNELS_MODE != 0u))
        #define ADC_ACCELEROMETER_DEFAULT_SE_NEG_INPUT    0u
    #else    /* miltiple channels or one single channel */
        #define ADC_ACCELEROMETER_DEFAULT_SE_NEG_INPUT    ADC_ACCELEROMETER_NEG_VREF
    #endif /* (ADC_ACCELEROMETER_TOTAL_CHANNELS_NUM == 1u) */
    #define ADC_ACCELEROMETER_DEFAULT_MUX_SWITCH0     0u
#elif (ADC_ACCELEROMETER_SINGLE_PRESENT != 0u)
    #define ADC_ACCELEROMETER_DEFAULT_SE_NEG_INPUT    ADC_ACCELEROMETER_NEG_OTHER
    #define ADC_ACCELEROMETER_DEFAULT_MUX_SWITCH0     0u
#else
    #define ADC_ACCELEROMETER_DEFAULT_SE_NEG_INPUT    0u
    #define ADC_ACCELEROMETER_DEFAULT_MUX_SWITCH0     0u
#endif /* ADC_ACCELEROMETER_DEFAULT_NEG_INPUT_SEL == ADC_ACCELEROMETER__VREF */

/* If the SAR is configured for multiple channels, always set SAR_HW_CTRL_NEGVREF to 1 */
#if(ADC_ACCELEROMETER_TOTAL_CHANNELS_NUM == 1u)
    #define ADC_ACCELEROMETER_DEFAULT_HW_CTRL_NEGVREF 0u
#else 
    #define ADC_ACCELEROMETER_DEFAULT_HW_CTRL_NEGVREF ADC_ACCELEROMETER_SAR_HW_CTRL_NEGVREF
#endif /* (ADC_ACCELEROMETER_TOTAL_CHANNELS_NUM == 1u) */    


#if(ADC_ACCELEROMETER_DEFAULT_ALT_RESOLUTION_SEL == ADC_ACCELEROMETER__RES8)
    #define ADC_ACCELEROMETER_DEFAULT_ALT_RESOLUTION     (ADC_ACCELEROMETER_ALT_RESOLUTION_8BIT)
    #define ADC_ACCELEROMETER_DEFAULT_MAX_WRK_ALT        (ADC_ACCELEROMETER_SAR_WRK_MAX_8BIT)
#else
    #define ADC_ACCELEROMETER_DEFAULT_ALT_RESOLUTION     (ADC_ACCELEROMETER_ALT_RESOLUTION_10BIT)
    #define ADC_ACCELEROMETER_DEFAULT_MAX_WRK_ALT        (ADC_ACCELEROMETER_SAR_WRK_MAX_10BIT)
#endif /* End ADC_ACCELEROMETER_DEFAULT_ALT_RESOLUTION_SEL == ADC_ACCELEROMETER__RES8 */

#if(ADC_ACCELEROMETER_DEFAULT_JUSTIFICATION_SEL == ADC_ACCELEROMETER__RIGHT)
    #define ADC_ACCELEROMETER_DEFAULT_JUSTIFICATION  ADC_ACCELEROMETER_DATA_ALIGN_RIGHT
#else
    #define ADC_ACCELEROMETER_DEFAULT_JUSTIFICATION  ADC_ACCELEROMETER_DATA_ALIGN_LEFT
#endif /* ADC_ACCELEROMETER_DEFAULT_JUSTIFICATION_SEL == ADC_ACCELEROMETER__RIGHT */

#if(ADC_ACCELEROMETER_DEFAULT_DIFF_RESULT_FORMAT_SEL == ADC_ACCELEROMETER__FSIGNED)
    #define ADC_ACCELEROMETER_DEFAULT_DIFF_RESULT_FORMAT ADC_ACCELEROMETER_DIFF_SIGNED_RESULT
#else
    #define ADC_ACCELEROMETER_DEFAULT_DIFF_RESULT_FORMAT ADC_ACCELEROMETER_DIFF_UNSIGNED_RESULT
#endif /* ADC_ACCELEROMETER_DEFAULT_DIFF_RESULT_FORMAT_SEL == ADC_ACCELEROMETER__FSIGNED */

#if(ADC_ACCELEROMETER_DEFAULT_SE_RESULT_FORMAT_SEL == ADC_ACCELEROMETER__FSIGNED)
    #define ADC_ACCELEROMETER_DEFAULT_SE_RESULT_FORMAT ADC_ACCELEROMETER_SE_SIGNED_RESULT
#else
    #define ADC_ACCELEROMETER_DEFAULT_SE_RESULT_FORMAT ADC_ACCELEROMETER_SE_UNSIGNED_RESULT
#endif /* ADC_ACCELEROMETER_DEFAULT_SE_RESULT_FORMAT_SEL == ADC_ACCELEROMETER__FSIGNED */

#if(ADC_ACCELEROMETER_DEFAULT_SAMPLE_MODE_SEL == ADC_ACCELEROMETER__FREERUNNING)
    #define ADC_ACCELEROMETER_DSI_TRIGGER        0u
#else /* Firmware trigger */
    #define ADC_ACCELEROMETER_DSI_TRIGGER        (ADC_ACCELEROMETER_DSI_TRIGGER_EN | ADC_ACCELEROMETER_DSI_SYNC_TRIGGER)
#endif /* End ADC_ACCELEROMETER_DEFAULT_SAMPLE_MODE == ADC_ACCELEROMETER__FREERUNNING */

#if(ADC_ACCELEROMETER_INJ_CHANNEL_ENABLED)
    #define ADC_ACCELEROMETER_SAR_INTR_MASK      (ADC_ACCELEROMETER_EOS_MASK | ADC_ACCELEROMETER_INJ_EOC_MASK)
#else
    #define ADC_ACCELEROMETER_SAR_INTR_MASK      (ADC_ACCELEROMETER_EOS_MASK)
#endif /* ADC_ACCELEROMETER_INJ_CHANNEL_ENABLED*/

#if(ADC_ACCELEROMETER_DEFAULT_AVG_MODE == ADC_ACCELEROMETER__FIXEDRESOLUTION)
    #define ADC_ACCELEROMETER_AVG_SHIFT_MODE     ADC_ACCELEROMETER_AVG_SHIFT
#else
    #define ADC_ACCELEROMETER_AVG_SHIFT_MODE     0u
#endif /* End ADC_ACCELEROMETER_DEFAULT_AVG_MODE */

#define ADC_ACCELEROMETER_COMPARE_MODE           (uint32)((uint32)(ADC_ACCELEROMETER_DEFAULT_COMPARE_MODE) \
                                                << ADC_ACCELEROMETER_CMP_OFFSET)

#if(ADC_ACCELEROMETER_TOTAL_CHANNELS_NUM > 1u)
    #define ADC_ACCELEROMETER_DEFAULT_SWITCH_CONF    0u
#else /* Disable SAR sequencer from enabling routing switches in single channel mode */
    #define ADC_ACCELEROMETER_DEFAULT_SWITCH_CONF    ADC_ACCELEROMETER_SWITCH_DISABLE
#endif /* End ADC_ACCELEROMETER_TOTAL_CHANNELS_NUM > 1 */

#define ADC_ACCELEROMETER_DEFAULT_POWER \
       ((ADC_ACCELEROMETER_NOMINAL_CLOCK_FREQ > (ADC_ACCELEROMETER_MAX_FREQUENCY / 4)) ? ADC_ACCELEROMETER_NORMAL_PWR : \
       ((ADC_ACCELEROMETER_NOMINAL_CLOCK_FREQ > (ADC_ACCELEROMETER_MAX_FREQUENCY / 8)) ? ADC_ACCELEROMETER_HALF_PWR : \
                                                                                       ADC_ACCELEROMETER_QUARTER_PWR))

#define ADC_ACCELEROMETER_DEFAULT_CTRL_REG_CFG       (ADC_ACCELEROMETER_DEFAULT_VREF_SOURCE \
                                                   | ADC_ACCELEROMETER_DEFAULT_SE_NEG_INPUT \
                                                   | ADC_ACCELEROMETER_DEFAULT_HW_CTRL_NEGVREF \
                                                   | ADC_ACCELEROMETER_DEFAULT_POWER \
                                                   | ADC_ACCELEROMETER_DSI_SYNC_CONFIG) \
                                                   | ADC_ACCELEROMETER_DEFAULT_SWITCH_CONF

#define ADC_ACCELEROMETER_DEFAULT_SAMPLE_CTRL_REG_CFG (ADC_ACCELEROMETER_DEFAULT_DIFF_RESULT_FORMAT \
                                                    | ADC_ACCELEROMETER_DEFAULT_SE_RESULT_FORMAT \
                                                    | ADC_ACCELEROMETER_DEFAULT_JUSTIFICATION \
                                                    | ADC_ACCELEROMETER_DEFAULT_ALT_RESOLUTION \
                                           | (uint8)(ADC_ACCELEROMETER_DEFAULT_AVG_SAMPLES_NUM \
                                                   << ADC_ACCELEROMETER_AVG_CNT_OFFSET) \
                                                    | ADC_ACCELEROMETER_AVG_SHIFT_MODE \
                                                    | ADC_ACCELEROMETER_DSI_TRIGGER \
                                                    | ADC_ACCELEROMETER_EOS_DSI_OUT_EN)

#define ADC_ACCELEROMETER_DEFAULT_RANGE_THRES_REG_CFG (ADC_ACCELEROMETER_DEFAULT_LOW_LIMIT \
            | (uint32)((uint32)ADC_ACCELEROMETER_DEFAULT_HIGH_LIMIT << ADC_ACCELEROMETER_RANGE_HIGH_OFFSET))

#define ADC_ACCELEROMETER_DEFAULT_SAMPLE_TIME01_REG_CFG (ADC_ACCELEROMETER_DEFAULT_ACLKS_NUM \
            | (uint32)((uint32)ADC_ACCELEROMETER_DEFAULT_BCLKS_NUM << ADC_ACCELEROMETER_SAMPLE_TIME13_OFFSET))

#define ADC_ACCELEROMETER_DEFAULT_SAMPLE_TIME23_REG_CFG (ADC_ACCELEROMETER_DEFAULT_CCLKS_NUM \
            | (uint32)((uint32)ADC_ACCELEROMETER_DEFAULT_DCLKS_NUM << ADC_ACCELEROMETER_SAMPLE_TIME13_OFFSET))


#endif /* End CY_ADC_SAR_SEQ_ADC_ACCELEROMETER_H */


/* [] END OF FILE */
