/*******************************************************************************
 * File Name: project.h
 * PSoC Creator 3.0 Component Pack 7
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <PSOC5.h>
#include <PSOC5_SPI_UART.h>
#include <PSOC5_PINS.h>
#include <PSOC5_SPI_UART_PVT.h>
#include <PSOC5_PVT.h>
#include <Vin.h>
#include <Vin_aliases.h>
#include <ADC_ACCELEROMETER.h>
#include <Vin_Y.h>
#include <Vin_Y_aliases.h>
#include <Vin_Z.h>
#include <Vin_Z_aliases.h>
#include <BLUE.h>
#include <PSOC5_rx.h>
#include <PSOC5_rx_aliases.h>
#include <PSOC5_SCBCLK.h>
#include <PSOC5_tx.h>
#include <PSOC5_tx_aliases.h>
#include <ADC_ACCELEROMETER_intClock.h>
#include <ADC_ACCELEROMETER_IRQ.h>
#include <BLUE_IntClock.h>
#include <core_cm0_psoc4.h>
#include <core_cm0.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cyPm.h>
#include <cytypes.h>
#include <cypins.h>
#include <core_cmFunc.h>
#include <core_cmInstr.h>

/*[]*/

